# Generated by Django 5.1.4 on 2024-12-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('acc', models.IntegerField(primary_key='acc', serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobileno', models.IntegerField()),
                ('pancode', models.IntegerField()),
                ('aadharcode', models.IntegerField()),
            ],
        ),
    ]
